services:
    kernel.listener.json_response_listener :
      class:     ApiBundle\EventListener\JsonResponseListener
      tags:
          - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
